"""Add order fulfillment fields

Revision ID: 91a5fedf6109
Revises: 762181f5b361
Create Date: 2026-05-18 00:16:31.164357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a5fedf6109'
down_revision = '762181f5b361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dispatched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fulfillment_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('fulfillment_notes')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('dispatched_at')
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
